# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_video_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddVideoWindows(object):
    def setupUi(self, AddVideoWindows):
        AddVideoWindows.setObjectName("AddVideoWindows")
        AddVideoWindows.resize(678, 308)
        AddVideoWindows.setStyleSheet(
            "QWidget {\n"
            "    background-color:rgb(82, 82, 82);\n"
            "}\n"
            "QDialog {\n"
            "    background-color:rgb(82, 82, 82);\n"
            "}\n"
            "QTextEdit {\n"
            "    background-color:rgb(42, 42, 42);\n"
            "    color: rgb(0, 255, 0);\n"
            "}\n"
            "QPushButton{\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-bottom-color: rgb(58, 58, 58);\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: rgb(255, 255, 255);\n"
            "    padding: 2px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
            "    border-bottom-color: rgb(115, 115, 115);\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: rgb(255, 255, 255);\n"
            "    padding: 2px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-bottom-color: rgb(58, 58, 58);\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: rgb(255, 255, 255);\n"
            "    padding: 2px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
            "}\n"
            "QPushButton:disabled{\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-bottom-color: rgb(58, 58, 58);\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: rgb(0, 0, 0);\n"
            "    padding: 2px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
            "}\n"
            "QLineEdit {\n"
            "    border-width: 1px; border-radius: 4px;\n"
            "    border-color: rgb(58, 58, 58);\n"
            "    border-style: inset;\n"
            "    padding: 0 8px;\n"
            "    color: rgb(255, 255, 255);\n"
            "    background:rgb(100, 100, 100);\n"
            "    selection-background-color: rgb(187, 187, 187);\n"
            "    selection-color: rgb(60, 63, 65);\n"
            "}\n"
            "QLabel {\n"
            "    color:rgb(255,255,255);    \n"
            "}\n"
            "QProgressBar {\n"
            "    text-align: center;\n"
            "    color: rgb(240, 240, 240);\n"
            "    border-width: 1px; \n"
            "    border-radius: 10px;\n"
            "    border-color: rgb(58, 58, 58);\n"
            "    border-style: inset;\n"
            "    background-color:rgb(77,77,77);\n"
            "}\n"
            "QProgressBar::chunk {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QMenuBar {\n"
            "    background:rgb(82, 82, 82);\n"
            "}\n"
            "QMenuBar::item {\n"
            "    color:rgb(223,219,210);\n"
            "    spacing: 3px;\n"
            "    padding: 1px 4px;\n"
            "    background: transparent;\n"
            "}\n"
            "\n"
            "QMenuBar::item:selected {\n"
            "    background:rgb(115, 115, 115);\n"
            "}\n"
            "QMenu::item:selected {\n"
            "    color:rgb(255,255,255);\n"
            "    border-width:2px;\n"
            "    border-style:solid;\n"
            "    padding-left:18px;\n"
            "    padding-right:8px;\n"
            "    padding-top:2px;\n"
            "    padding-bottom:3px;\n"
            "    background:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-bottom-color: rgb(58, 58, 58);\n"
            "    border-bottom-width: 1px;\n"
            "}\n"
            "QMenu::item {\n"
            "    color:rgb(223,219,210);\n"
            "    background-color:rgb(78,78,78);\n"
            "    padding-left:20px;\n"
            "    padding-top:4px;\n"
            "    padding-bottom:4px;\n"
            "    padding-right:10px;\n"
            "}\n"
            "QMenu{\n"
            "    background-color:rgb(78,78,78);\n"
            "}\n"
            "QTabWidget {\n"
            "    color:rgb(0,0,0);\n"
            "    background-color:rgb(247,246,246);\n"
            "}\n"
            "QTabWidget::pane {\n"
            "        border-color: rgb(77,77,77);\n"
            "        background-color:rgb(101,101,101);\n"
            "        border-style: solid;\n"
            "        border-width: 1px;\n"
            "        border-radius: 6px;\n"
            "}\n"
            "QTabBar::tab {\n"
            "    padding:2px;\n"
            "    color:rgb(250,250,250);\n"
            "      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
            "    border-style: solid;\n"
            "    border-width: 2px;\n"
            "      border-top-right-radius:4px;\n"
            "   border-top-left-radius:4px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
            "    border-bottom-color: rgb(101,101,101);\n"
            "}\n"
            "QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
            "      background-color:rgb(101,101,101);\n"
            "      margin-left: 0px;\n"
            "      margin-right: 1px;\n"
            "}\n"
            "QTabBar::tab:!selected {\n"
            "        margin-top: 1px;\n"
            "        margin-right: 1px;\n"
            "}\n"
            "QCheckBox {\n"
            "    color:rgb(223,219,210);\n"
            "    padding: 2px;\n"
            "}\n"
            "QCheckBox:hover {\n"
            "    border-radius:4px;\n"
            "    border-style:solid;\n"
            "    padding-left: 1px;\n"
            "    padding-right: 1px;\n"
            "    padding-bottom: 1px;\n"
            "    padding-top: 1px;\n"
            "    border-width:1px;\n"
            "    border-color: rgb(87, 97, 106);\n"
            "    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 150), stop:1 rgba(93, 103, 113, 150));\n"
            "}\n"
            "QCheckBox::indicator:checked {\n"
            "    border-radius:4px;\n"
            "    border-style:solid;\n"
            "    border-width:1px;\n"
            "    border-color: rgb(180,180,180);\n"
            "      background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
            "}\n"
            "QCheckBox::indicator:unchecked {\n"
            "    border-radius:4px;\n"
            "    border-style:solid;\n"
            "    border-width:1px;\n"
            "    border-color: rgb(87, 97, 106);\n"
            "      background-color:rgb(255,255,255);\n"
            "}\n"
            "QStatusBar {\n"
            "    color:rgb(240,240,240);\n"
            "}\n"
            "\n"
            "QPushButton{\n"
            "    border-style: solid;\n"
            "    border-color: #050a0e;\n"
            "    border-width: 1px;\n"
            "    border-radius: 5px;\n"
            "    color: #d3dae3;\n"
            "    padding: 2px;\n"
            "    background-color: #100E19;\n"
            "}\n"
            "QPushButton::default{\n"
            "    border-style: solid;\n"
            "    border-color: #050a0e;\n"
            "    border-width: 1px;\n"
            "    border-radius: 5px;\n"
            "    color: #FFFFFF;\n"
            "    padding: 2px;\n"
            "    background-color: #151a1e;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #C0DB50, stop:0.4 #C0DB50, stop:0.5 #100E19, stop:1 #100E19);\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #C0DB50, stop:1 #C0DB50);\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
            "    border-width: 2px;\n"
            "    border-radius: 1px;\n"
            "    color: #d3dae3;\n"
            "    padding: 2px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #d33af1, stop:0.4 #d33af1, stop:0.5 #100E19, stop:1 #100E19);\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #d33af1, stop:1 #d33af1);\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
            "    border-width: 2px;\n"
            "    border-radius: 1px;\n"
            "    color: #d3dae3;\n"
            "    padding: 2px;\n"
            "}"
        )
        self.verticalLayoutWidget = QtWidgets.QWidget(AddVideoWindows)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 621, 270))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b_choice_video = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(14)
        self.b_choice_video.setFont(font)
        self.b_choice_video.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_choice_video.setObjectName("b_choice_video")
        self.verticalLayout.addWidget(self.b_choice_video)
        self.label_choice = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_choice.sizePolicy().hasHeightForWidth())
        self.label_choice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(10)
        self.label_choice.setFont(font)
        self.label_choice.setText("")
        self.label_choice.setAlignment(QtCore.Qt.AlignCenter)
        self.label_choice.setObjectName("label_choice")
        self.verticalLayout.addWidget(self.label_choice)
        self.cb_day = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cb_day.setObjectName("cb_day")
        self.verticalLayout.addWidget(self.cb_day)
        self.b_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(14)
        self.b_add.setFont(font)
        self.b_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_add.setObjectName("b_add")
        self.verticalLayout.addWidget(self.b_add)
        self.b_back = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(14)
        self.b_back.setFont(font)
        self.b_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_back.setObjectName("b_back")
        self.verticalLayout.addWidget(self.b_back)
        self.min = QtWidgets.QPushButton(AddVideoWindows)
        self.min.setGeometry(QtCore.QRect(600, 0, 41, 41))
        self.min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min.setText("")
        self.min.setObjectName("min")
        self.exit = QtWidgets.QPushButton(AddVideoWindows)
        self.exit.setGeometry(QtCore.QRect(640, 0, 41, 41))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.line = QtWidgets.QFrame(AddVideoWindows)
        self.line.setGeometry(QtCore.QRect(0, 30, 601, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_day.setFont(font)
        list_days = [
            "Понедельник",
            "Вторник",
            "Среда",
            "Четверг",
            "Пятница",
            "Суббота",
            "Воскресенье",
        ]
        self.cb_day.clear()
        self.cb_day.addItems(list_days)

        self.retranslateUi(AddVideoWindows)
        QtCore.QMetaObject.connectSlotsByName(AddVideoWindows)

    def retranslateUi(self, AddVideoWindows):
        _translate = QtCore.QCoreApplication.translate
        AddVideoWindows.setWindowTitle(_translate("AddVideoWindows", "Dialog"))
        self.b_choice_video.setText(_translate("AddVideoWindows", "Выбрать видео"))
        self.b_add.setText(_translate("AddVideoWindows", "Добавить"))
        self.b_back.setText(_translate("AddVideoWindows", "Выйти из профиля"))
