# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimediaWidgets
from PyQt5.QtGui import QIcon, QFont
from PyQt5.QtCore import QDir, Qt, QUrl, QSize
from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import (
    QApplication,
    QFileDialog,
    QHBoxLayout,
    QLabel,
    QPushButton,
    QSizePolicy,
    QSlider,
    QStyle,
    QVBoxLayout,
    QWidget,
    QStatusBar,
)


class VideoPlayer(QWidget):
    def __init__(self, parent=None):
        super(VideoPlayer, self).__init__(parent)

        self.mediaPlayer = QMediaPlayer(None, QMediaPlayer.VideoSurface)

        btnSize = QSize(16, 16)
        videoWidget = QVideoWidget()

        self.playButton = QPushButton()
        self.playButton.setEnabled(False)
        self.playButton.setFixedHeight(24)
        self.playButton.setIconSize(btnSize)
        self.playButton.setIcon(self.style().standardIcon(QStyle.SP_MediaPlay))
        self.playButton.clicked.connect(self.play)

        self.positionSlider = QSlider(Qt.Horizontal)
        self.positionSlider.setRange(0, 0)
        self.positionSlider.sliderMoved.connect(self.setPosition)

        self.statusBar = QStatusBar()
        self.statusBar.setFont(QFont("Noto Sans", 7))
        self.statusBar.setFixedHeight(14)

        controlLayout = QHBoxLayout()
        controlLayout.setContentsMargins(0, 0, 0, 0)
        controlLayout.addWidget(self.playButton)
        controlLayout.addWidget(self.positionSlider)

        layout = QVBoxLayout()
        layout.addWidget(videoWidget)
        layout.addLayout(controlLayout)
        layout.addWidget(self.statusBar)

        self.setLayout(layout)

        self.mediaPlayer.setVideoOutput(videoWidget)
        self.mediaPlayer.stateChanged.connect(self.mediaStateChanged)
        self.mediaPlayer.positionChanged.connect(self.positionChanged)
        self.mediaPlayer.durationChanged.connect(self.durationChanged)
        self.mediaPlayer.error.connect(self.handleError)
        self.statusBar.showMessage("Ready")

    def choice(self, fileName):
        if fileName != "":
            self.mediaPlayer.setMedia(QMediaContent(QUrl.fromLocalFile(fileName)))
            self.playButton.setEnabled(True)
            self.statusBar.showMessage(fileName)
            self.play()

    def play(self):
        if self.mediaPlayer.state() == QMediaPlayer.PlayingState:
            self.mediaPlayer.pause()
        else:
            self.mediaPlayer.play()

    def mediaStateChanged(self, state):
        if self.mediaPlayer.state() == QMediaPlayer.PlayingState:
            self.playButton.setIcon(self.style().standardIcon(QStyle.SP_MediaPause))
        else:
            self.playButton.setIcon(self.style().standardIcon(QStyle.SP_MediaPlay))

    def positionChanged(self, position):
        self.positionSlider.setValue(position)

    def durationChanged(self, duration):
        self.positionSlider.setRange(0, duration)

    def setPosition(self, position):
        self.mediaPlayer.setPosition(position)

    def handleError(self):
        self.playButton.setEnabled(False)
        self.statusBar.showMessage("Error: " + self.mediaPlayer.errorString())


class Ui_AppWindow(object):
    def setupUi(self, AppWindow):
        AppWindow.setObjectName("AppWindow")
        AppWindow.resize(972, 766)
        AppWindow.setStyleSheet(
            "QDialog {\n"
            "    background-color:rgb(82, 82, 82);\n"
            "}\n"
            "QTextEdit {\n"
            "    background-color:rgb(42, 42, 42);\n"
            "    color: rgb(0, 255, 0);\n"
            "}\n"
            "QPushButton{\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-bottom-color: rgb(58, 58, 58);\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: rgb(255, 255, 255);\n"
            "    padding: 2px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
            "    border-bottom-color: rgb(115, 115, 115);\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: rgb(255, 255, 255);\n"
            "    padding: 2px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-bottom-color: rgb(58, 58, 58);\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: rgb(255, 255, 255);\n"
            "    padding: 2px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
            "}\n"
            "QPushButton:disabled{\n"
            "    border-style: outset;\n"
            "    border-width: 2px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-bottom-color: rgb(58, 58, 58);\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: rgb(0, 0, 0);\n"
            "    padding: 2px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
            "}\n"
            "QLineEdit {\n"
            "    border-width: 1px; border-radius: 4px;\n"
            "    border-color: rgb(58, 58, 58);\n"
            "    border-style: inset;\n"
            "    padding: 0 8px;\n"
            "    color: rgb(255, 255, 255);\n"
            "    background:rgb(100, 100, 100);\n"
            "    selection-background-color: rgb(187, 187, 187);\n"
            "    selection-color: rgb(60, 63, 65);\n"
            "}\n"
            "QLabel {\n"
            "    color:rgb(255,255,255);    \n"
            "}\n"
            "QProgressBar {\n"
            "    text-align: center;\n"
            "    color: rgb(240, 240, 240);\n"
            "    border-width: 1px; \n"
            "    border-radius: 10px;\n"
            "    border-color: rgb(58, 58, 58);\n"
            "    border-style: inset;\n"
            "    background-color:rgb(77,77,77);\n"
            "}\n"
            "QProgressBar::chunk {\n"
            "    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QMenuBar {\n"
            "    background:rgb(82, 82, 82);\n"
            "}\n"
            "QMenuBar::item {\n"
            "    color:rgb(223,219,210);\n"
            "    spacing: 3px;\n"
            "    padding: 1px 4px;\n"
            "    background: transparent;\n"
            "}\n"
            "\n"
            "QMenuBar::item:selected {\n"
            "    background:rgb(115, 115, 115);\n"
            "}\n"
            "QMenu::item:selected {\n"
            "    color:rgb(255,255,255);\n"
            "    border-width:2px;\n"
            "    border-style:solid;\n"
            "    padding-left:18px;\n"
            "    padding-right:8px;\n"
            "    padding-top:2px;\n"
            "    padding-bottom:3px;\n"
            "    background:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
            "    border-bottom-color: rgb(58, 58, 58);\n"
            "    border-bottom-width: 1px;\n"
            "}\n"
            "QMenu::item {\n"
            "    color:rgb(223,219,210);\n"
            "    background-color:rgb(78,78,78);\n"
            "    padding-left:20px;\n"
            "    padding-top:4px;\n"
            "    padding-bottom:4px;\n"
            "    padding-right:10px;\n"
            "}\n"
            "QMenu{\n"
            "    background-color:rgb(78,78,78);\n"
            "}\n"
            "QTabWidget {\n"
            "    color:rgb(0,0,0);\n"
            "    background-color:rgb(247,246,246);\n"
            "}\n"
            "QTabWidget::pane {\n"
            "        border-color: rgb(77,77,77);\n"
            "        background-color:rgb(101,101,101);\n"
            "        border-style: solid;\n"
            "        border-width: 1px;\n"
            "        border-radius: 6px;\n"
            "}\n"
            "QTabBar::tab {\n"
            "    padding:2px;\n"
            "    color:rgb(250,250,250);\n"
            "      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
            "    border-style: solid;\n"
            "    border-width: 2px;\n"
            "      border-top-right-radius:4px;\n"
            "   border-top-left-radius:4px;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
            "    border-bottom-color: rgb(101,101,101);\n"
            "}\n"
            "QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
            "      background-color:rgb(101,101,101);\n"
            "      margin-left: 0px;\n"
            "      margin-right: 1px;\n"
            "}\n"
            "QTabBar::tab:!selected {\n"
            "        margin-top: 1px;\n"
            "        margin-right: 1px;\n"
            "}\n"
            "QCheckBox {\n"
            "    color:rgb(223,219,210);\n"
            "    padding: 2px;\n"
            "}\n"
            "QCheckBox:hover {\n"
            "    border-radius:4px;\n"
            "    border-style:solid;\n"
            "    padding-left: 1px;\n"
            "    padding-right: 1px;\n"
            "    padding-bottom: 1px;\n"
            "    padding-top: 1px;\n"
            "    border-width:1px;\n"
            "    border-color: rgb(87, 97, 106);\n"
            "    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 150), stop:1 rgba(93, 103, 113, 150));\n"
            "}\n"
            "QCheckBox::indicator:checked {\n"
            "    border-radius:4px;\n"
            "    border-style:solid;\n"
            "    border-width:1px;\n"
            "    border-color: rgb(180,180,180);\n"
            "      background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
            "}\n"
            "QCheckBox::indicator:unchecked {\n"
            "    border-radius:4px;\n"
            "    border-style:solid;\n"
            "    border-width:1px;\n"
            "    border-color: rgb(87, 97, 106);\n"
            "      background-color:rgb(255,255,255);\n"
            "}\n"
            "QStatusBar {\n"
            "    color:rgb(240,240,240);\n"
            "}\n"
            "\n"
            "QPushButton{\n"
            "    border-style: solid;\n"
            "    border-color: #050a0e;\n"
            "    border-width: 1px;\n"
            "    border-radius: 5px;\n"
            "    color: #d3dae3;\n"
            "    padding: 2px;\n"
            "    background-color: #100E19;\n"
            "}\n"
            "QPushButton::default{\n"
            "    border-style: solid;\n"
            "    border-color: #050a0e;\n"
            "    border-width: 1px;\n"
            "    border-radius: 5px;\n"
            "    color: #FFFFFF;\n"
            "    padding: 2px;\n"
            "    background-color: #151a1e;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #C0DB50, stop:0.4 #C0DB50, stop:0.5 #100E19, stop:1 #100E19);\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #C0DB50, stop:1 #C0DB50);\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
            "    border-width: 2px;\n"
            "    border-radius: 1px;\n"
            "    color: #d3dae3;\n"
            "    padding: 2px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border-style: solid;\n"
            "    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #d33af1, stop:0.4 #d33af1, stop:0.5 #100E19, stop:1 #100E19);\n"
            "    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #d33af1, stop:1 #d33af1);\n"
            "    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
            "    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
            "    border-width: 2px;\n"
            "    border-radius: 1px;\n"
            "    color: #d3dae3;\n"
            "    padding: 2px;\n"
            "}"
        )
        self.min = QtWidgets.QPushButton(AppWindow)
        self.min.setGeometry(QtCore.QRect(890, 0, 41, 41))
        self.min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min.setText("")
        self.min.setObjectName("min")
        self.exit = QtWidgets.QPushButton(AppWindow)
        self.exit.setGeometry(QtCore.QRect(930, 0, 41, 41))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.verticalLayoutWidget = QtWidgets.QWidget(AppWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 37, 971, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_global = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_global.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_global.setObjectName("verticalLayout_global")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_train = QtWidgets.QWidget()
        self.tab_train.setObjectName("tab_train")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_train)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 10, 392, 236))
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_train)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(410, 10, 551, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_train = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_train.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_train.setObjectName("verticalLayout_train")
        self.label_train = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(14)
        self.label_train.setFont(font)
        self.label_train.setAlignment(QtCore.Qt.AlignCenter)
        self.label_train.setObjectName("label_train")
        self.verticalLayout_train.addWidget(self.label_train)
        self.comboBox_train = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(10)
        self.comboBox_train.setFont(font)
        self.comboBox_train.setObjectName("comboBox_train")
        self.verticalLayout_train.addWidget(self.comboBox_train)
        # Добавление кнопки тренировки
        self.b_train = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(14)
        self.b_train.setFont(font)
        self.b_train.setObjectName("b_exit")
        self.verticalLayout_train.addWidget(self.b_train)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_train)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 259, 951, 401))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_video = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_video.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_video.setObjectName("verticalLayout_video")

        # Добавляем плеер
        self.video_train = VideoPlayer()
        self.video_train.setObjectName("video_train")
        self.verticalLayout_video.addWidget(self.video_train)

        self.tabWidget.addTab(self.tab_train, "")
        self.tab_stat = QtWidgets.QWidget()
        self.tab_stat.setObjectName("tab_stat")
        self.tabWidget.addTab(self.tab_stat, "")

        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_stat)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(9, 259, 951, 401))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_stat = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_stat.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_stat.setObjectName("verticalLayout_stat")
        self.lable_stat = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(14)
        self.lable_stat.setFont(font)
        self.lable_stat.setObjectName("lable_stat")
        self.verticalLayout_stat.addWidget(self.lable_stat)
        self.verticalLayout_global.addWidget(self.tabWidget)
        self.b_exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(14)
        self.b_exit.setFont(font)
        self.b_exit.setObjectName("b_exit")
        self.verticalLayout_global.addWidget(self.b_exit)
        self.line = QtWidgets.QFrame(AppWindow)
        self.line.setGeometry(QtCore.QRect(0, 30, 891, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(AppWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AppWindow)

    def retranslateUi(self, AppWindow):
        _translate = QtCore.QCoreApplication.translate
        AppWindow.setWindowTitle(_translate("AppWindow", "Dialog"))
        self.label_train.setText(_translate("AppWindow", "Доступные тренировки"))
        self.lable_stat.setText(
            _translate("AppWindow", "Количество времени тренировок на текущей недели:")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_train),
            _translate("AppWindow", "Тренировки"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_stat), _translate("AppWindow", "Статистика")
        )
        self.b_train.setText(_translate("AppWindow", "Тренироваться"))
        self.b_exit.setText(_translate("AppWindow", "Выход"))
